---
title: "Teaching"
subtitle: "Courses taught by Murat Abus at Arkansas State University."
---

I teach courses in political science at the Department of Government, Law & Policy. My approach emphasizes the following: developing written and spoken presentation and argumentation skills with a heavy focus on critical thinking (partially through repeated question-answer sequences), real-world applications and implications of the subject material, hands-on data analysis with an eye on answering real-world inquiries.

## Teaching Interests

Introduction to Data Analysis · Data Visualization · Applied Data Analysis · Advanced Data Analysis · Introduction to Comparative Politics · Political Behavior · Election Science · Local Elections and Local Politics · Authoritarianism & Populism · Media and Politics · Introduction to Political Psychology · Comparing Democracies / Comparative Political Behavior · Public Opinion and Political Parties · Russian State & Politics · Politics of Developing Countries

## Fall 2026
I am teaching three courses in Fall 2026:

- **PLSC 30453** Introduction to Political Analysis (undergraduate): [30453 Syllabus](https://astate.simplesyllabus.com/doc/cl7v72iuu/2026-Fall-PLSC-30453-001-INTRO-TO-POLITICAL-ANALYSIS?mode=view)

- **PLSC 33203** Introduction to Comparative Politics (undergraduate): [33203 Syllabus](https://astate.simplesyllabus.com/doc/ufu7zp2qv/2026-Fall-PLSC-33203-001-INTRO-TO-COMPARATIVE-POLITICS?mode=view)

- **PLSC 6013** Advanced Political Analysis (graduate): Syllabus and other pertinent information will be posted here in early August. 

If you are a prospective or enrolled student and want to know more in the meantime, [email me](mailto:mabus@astate.edu).

## Office Hours

- MF 14:00-16:30 HSS 3052.

- For meeting outside of office hours, you may [schedule a meeting](https://outlook.office.com/bookwithme/user/746d194683be4d4c81655d3028861cb4@astate.edu?anonymous&ismsaljsauthenabled&ep=pcard)
